package com.redhat.dm7.demo.ruleunits.chained.units;
unit OrchestrationUnit

rule "Schedule units."
when
then
	System.out.println("Scheduling units.");
	/*
	 * Schedule the execution of the rule-units so that the units run in the order: FilterUnit, AdultUnit, OutputUnit.
	 */
	 System.out.println("Lab: Schedule the execution of the rule-units so that the units run in the order: FilterUnit, AdultUnit, OutputUnit.");
	
end