package com.redhat.dm7.demo.ruleunits.unit;
unit AdultUnitWithUnitVar

import com.redhat.dm7.demo.ruleunits.model.Person;
import com.redhat.dm7.demo.ruleunits.unit.AdultUnit;


rule "AdultWithUnitVar"
when
	$p:Person(age >= adultAge) from persons
then
	System.out.println($p.getName() + " is adult and greater than " + adultAge);
end


rule "Adult OOPath With UnitVar"
when
	$p: /persons[age >= adultAge]
then
	System.out.println($p.getName() + " is adult OOPath and greater than " + adultAge);
end
